// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	utils "github.com/AshokaJS/DhakadFitness/utils"
	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: ctx, email, role, password
func (_m *AuthService) Authenticate(ctx context.Context, email string, role string, password string) (*utils.User, error) {
	ret := _m.Called(ctx, email, role, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *utils.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*utils.User, error)); ok {
		return rf(ctx, email, role, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *utils.User); ok {
		r0 = rf(ctx, email, role, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, email, role, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Signup provides a mock function with given fields: ctx, username, email, password, role
func (_m *AuthService) Signup(ctx context.Context, username string, email string, password string, role string) error {
	ret := _m.Called(ctx, username, email, password, role)

	if len(ret) == 0 {
		panic("no return value specified for Signup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, username, email, password, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
