// Code generated by mockery v2.53.0. DO NOT EDIT.

package gym

import mock "github.com/stretchr/testify/mock"

// MockGymRepository is an autogenerated mock type for the GymRepository type
type MockGymRepository struct {
	mock.Mock
}

type MockGymRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGymRepository) EXPECT() *MockGymRepository_Expecter {
	return &MockGymRepository_Expecter{mock: &_m.Mock}
}

// AddPlan provides a mock function with given fields: plan
func (_m *MockGymRepository) AddPlan(plan Plan) (string, error) {
	ret := _m.Called(plan)

	if len(ret) == 0 {
		panic("no return value specified for AddPlan")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(Plan) (string, error)); ok {
		return rf(plan)
	}
	if rf, ok := ret.Get(0).(func(Plan) string); ok {
		r0 = rf(plan)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(Plan) error); ok {
		r1 = rf(plan)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGymRepository_AddPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPlan'
type MockGymRepository_AddPlan_Call struct {
	*mock.Call
}

// AddPlan is a helper method to define mock.On call
//   - plan Plan
func (_e *MockGymRepository_Expecter) AddPlan(plan interface{}) *MockGymRepository_AddPlan_Call {
	return &MockGymRepository_AddPlan_Call{Call: _e.mock.On("AddPlan", plan)}
}

func (_c *MockGymRepository_AddPlan_Call) Run(run func(plan Plan)) *MockGymRepository_AddPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(Plan))
	})
	return _c
}

func (_c *MockGymRepository_AddPlan_Call) Return(_a0 string, _a1 error) *MockGymRepository_AddPlan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGymRepository_AddPlan_Call) RunAndReturn(run func(Plan) (string, error)) *MockGymRepository_AddPlan_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGym provides a mock function with given fields: gym
func (_m *MockGymRepository) CreateGym(gym *GymStruct) (string, error) {
	ret := _m.Called(gym)

	if len(ret) == 0 {
		panic("no return value specified for CreateGym")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*GymStruct) (string, error)); ok {
		return rf(gym)
	}
	if rf, ok := ret.Get(0).(func(*GymStruct) string); ok {
		r0 = rf(gym)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*GymStruct) error); ok {
		r1 = rf(gym)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGymRepository_CreateGym_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGym'
type MockGymRepository_CreateGym_Call struct {
	*mock.Call
}

// CreateGym is a helper method to define mock.On call
//   - gym *GymStruct
func (_e *MockGymRepository_Expecter) CreateGym(gym interface{}) *MockGymRepository_CreateGym_Call {
	return &MockGymRepository_CreateGym_Call{Call: _e.mock.On("CreateGym", gym)}
}

func (_c *MockGymRepository_CreateGym_Call) Run(run func(gym *GymStruct)) *MockGymRepository_CreateGym_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*GymStruct))
	})
	return _c
}

func (_c *MockGymRepository_CreateGym_Call) Return(_a0 string, _a1 error) *MockGymRepository_CreateGym_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGymRepository_CreateGym_Call) RunAndReturn(run func(*GymStruct) (string, error)) *MockGymRepository_CreateGym_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePlan provides a mock function with given fields: planId
func (_m *MockGymRepository) DeletePlan(planId int) error {
	ret := _m.Called(planId)

	if len(ret) == 0 {
		panic("no return value specified for DeletePlan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(planId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGymRepository_DeletePlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePlan'
type MockGymRepository_DeletePlan_Call struct {
	*mock.Call
}

// DeletePlan is a helper method to define mock.On call
//   - planId int
func (_e *MockGymRepository_Expecter) DeletePlan(planId interface{}) *MockGymRepository_DeletePlan_Call {
	return &MockGymRepository_DeletePlan_Call{Call: _e.mock.On("DeletePlan", planId)}
}

func (_c *MockGymRepository_DeletePlan_Call) Run(run func(planId int)) *MockGymRepository_DeletePlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockGymRepository_DeletePlan_Call) Return(_a0 error) *MockGymRepository_DeletePlan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGymRepository_DeletePlan_Call) RunAndReturn(run func(int) error) *MockGymRepository_DeletePlan_Call {
	_c.Call.Return(run)
	return _c
}

// GetGymProfile provides a mock function with given fields: gymId
func (_m *MockGymRepository) GetGymProfile(gymId int) (*[]GetGym, error) {
	ret := _m.Called(gymId)

	if len(ret) == 0 {
		panic("no return value specified for GetGymProfile")
	}

	var r0 *[]GetGym
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*[]GetGym, error)); ok {
		return rf(gymId)
	}
	if rf, ok := ret.Get(0).(func(int) *[]GetGym); ok {
		r0 = rf(gymId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]GetGym)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(gymId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGymRepository_GetGymProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGymProfile'
type MockGymRepository_GetGymProfile_Call struct {
	*mock.Call
}

// GetGymProfile is a helper method to define mock.On call
//   - gymId int
func (_e *MockGymRepository_Expecter) GetGymProfile(gymId interface{}) *MockGymRepository_GetGymProfile_Call {
	return &MockGymRepository_GetGymProfile_Call{Call: _e.mock.On("GetGymProfile", gymId)}
}

func (_c *MockGymRepository_GetGymProfile_Call) Run(run func(gymId int)) *MockGymRepository_GetGymProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockGymRepository_GetGymProfile_Call) Return(_a0 *[]GetGym, _a1 error) *MockGymRepository_GetGymProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGymRepository_GetGymProfile_Call) RunAndReturn(run func(int) (*[]GetGym, error)) *MockGymRepository_GetGymProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGymRepository creates a new instance of MockGymRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGymRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGymRepository {
	mock := &MockGymRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
